# Generated by Django 4.2.28 on 2026-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stiv_app', '0002_remove_car_available_remove_car_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
